pipeline {
    agent {
        docker {
            image 'nginx:latest'
        }
    }
    stages {
        stage('Front-end') {
            steps {
                sh 'nginx -v'
            }
        }

       stage('Back-end') {
    agent {
        docker {
            image 'python:3.9'
        }
    }
    steps {
        sh 'echo "Before Python command"'
        sh 'python -c "print(\'This is a Python backend\')"'
        sh 'echo "After Python command"'
    }
}

        stage('Data-Base') {
            agent {
                docker {
                    image 'postgres:latest'
                }
            }
            steps {
                sh 'psql --version'
            }
        }
    }
}
