pipeline {
    agent any // Use any available Jenkins agent

    stages {
        stage('Front-end') {
            agent {
                docker {
                    image 'nginx:latest'
                }
            }
            steps {
                sh 'echo "Front-end is running"'
            }
        }

        stage('Back-end') {
            agent {
                docker {
                    image 'node:14'
                }
            }
            steps {
                sh 'echo "Back-end is running"'
            }
        }

        stage('Database') {
            agent {
                docker {
                    image 'postgres:latest'
                }
            }
            steps {
                sh 'echo "Database is running"'
            }
        }
    }
}
